friends = ["Kevin" ,"Karen", "Jim" ,"Hop", 2, True]
print(friends[-1])
print(friends[1:3])
print(friends[2:])
friends[4] = 5
print(friends[1:6])

numbers = [1,2,3,4,5,6,7,8]
friends.extend(numbers)
print(friends)
friends.append("creed")
print(friends)
friends.insert(1,"ANKIT")
print(friends)
friends.remove("Hop")
print(friends)
friends.pop()
print(friends)
print(friends.index("Kevin"))
friends.insert(2, "ANKIT")
print(friends.count("ANKIT"))
kaim = [4,7,6,7,9,1,3,0]
kaim.reverse()
kaim.sort()
print(kaim)
kaim.reverse()
kaim.insert(2, 7)
print(kaim.count(7))
friends.extend(kaim)
print(friends)
friends2 = friends.copy()
friends.clear()
print(friends)
print(friends2)